# Tracker.gg View Bot

# Tool settings
# USE API LINKS TO AVOID BEING CACHED BY CLOUDFLARE!
link_to_boost: "https://api.tracker.gg/api/v2/valorant/standard/profile/riot/VIBHANSH%231053"
proxies_file: "src/input/proxies.txt"
threads: 10
